### ISSUE TITLE
hy-tsoha vertaisarviointi

### ISSUE THREAD

**Issue by iw545** [AlanenR/satellite-data-subscription-service#1]
Sovelluksella on asiaan kuuluvasti toteutettu rakenne, mihin on hyvä alkaa kehittämään lisää toiminnallisuutta. Kaikki vaikuttaisi toimivan tähän mennessä niin kuin pitää, eikä sovelluksessa ole mitään epäselvyyksiä ulkoasussa. Klikattavat linkit ja hakupalkki ovat sijoitettu loogisesti, mikä helpottaa navigointia sovelluksessa.  
  
Tässä vielä pari vinkkiä sovelluksen parantamisen kannalta, samalla ottaen huomioon readme.md dokumentaatiossa käsiteltyjä tietoja:  

- user_roles: Olisikohan hyvä, jos tämän tiedon sisällyttäisi suoraan "users" taulukkoon (admin FALSE / TRUE tyylisesti esim, en ihan täysin tosin tiedä onko tuo hyvä tapa toteuttaa tämä), jos rooleja on vain esim. normaali käyttäjä ja admin. Jos rooleja on tuota enemmän niin sitten ymmärrän että niille on hyvä olla oma taulukko.  
  
- data_categories taulukosta ei käy tarpeeksi selväksi sen merkitys sovelluksessa, enemmän tietoa siitä voisi päivittää readme.md tiedostoon

**Comment by AlanenR** [comment]
Kiitos palautteesta :)
